### ISSUE TITLE
Page collex Persée

### ISSUE THREAD

**Issue by SophieForcadell** [SciencesPoDRIS/archelec4#1]
**Quel est le problème ?**
L'intitulé du lien "crédits" situé en bas de la page n'est pas correct
Absence de lien à partir de cet intitulé 

**Quel est le comportement attendu ?**
Remplacer l'intitulé "crédits" par "CollEx-Persée"
Lier vers une page web
Intégrer le contenu à partir de cette source : https://docs.google.com/document/d/1zO9LBMaluKcLJGAAPCNMRrfg4z9jmGp_lMytCy4B6pc/edit

**Comment reproduire le problème ?**

1. aller à cette URL: https://archelec.sciencespo.fr/
2. cliquer sur l'intitulé "crédits" en bas de page

**Comment by paulgirard** [comment]
Ne faut il pas prévoir un contenu crédit indiquant qui a participé au projet ? 
On peut aussi ajotuer un lien vers collEx-Persée.

**Comment by SophieForcadell** [comment]
En fait c'est bien ce qui est prévu dans le texte CollEx :https://docs.google.com/document/d/1zO9LBMaluKcLJGAAPCNMRrfg4z9jmGp_lMytCy4B6pc/edit
