### ISSUE TITLE
Filtre âge

### ISSUE THREAD

**Issue by paulgirard** [SciencesPoDRIS/archelec4#16]
Les tranches d'âge ne sont pas très explicites.

- [x] On change le label en "Tranche d'âge"
- [x] on transforme les valeurs en "entre 20 et 29 ans”.

**Comment by sim51** [comment]
![image](https://user-images.githubusercontent.com/231657/122894201-46dd9e80-d347-11eb-9c43-615950160478.png)

The issue on the value is still here, but only for the data that comes from IA (not the computed one, which are fine now)
