### ISSUE TITLE
PAGE Profession de foi : lien licence CC dans un nouvel onglet

### ISSUE THREAD

**Issue by SophieForcadell** [SciencesPoDRIS/archelec4#2]
**Quel est le problème ?**
Le lien vers la licence CC ne s'ouvre pas sur un nouvel onglet

**Quel est le comportement attendu ?**
Le lien s'ouvre sur un nouvel onglet

**Comment reproduire le problème ?**

1. aller à cette URL: https://archelec.sciencespo.fr/profession/EL009_L_1958_11_001_01_1_PF_07
2. cliquer sur l'intitulé Licence
3. constater l'erreur

**Comment by paulgirard** [comment]
Solutions adoptée:
pour les trois liens de la partie accès document : ajouter une icone et ouvrir le lien dans un nouvel onglet
