### ISSUE TITLE
Ordre des valeurs de champs prise en compte des accents

### ISSUE THREAD

**Issue by paulgirard** [SciencesPoDRIS/archelec4#22]
école n'est pas proche de "e" dans Associations

**Comment by sim51** [comment]
Not simple, because it's a sort inside an aggregation, and we can't define the sort mechanism in the ES query.
So it's the default ES sort order .

Need to investigate more to know how to correct it

**Comment by paulgirard** [comment]
@diegantobass @SophieForcadell il faut qu'on discute de ça.

On pourrait mettre en place ce sort malgré les accents mais en regradant comment faire ça (bizarement c'est beaucoup plus compliqué que l'on pourrait le penser) on se demande si on ne ferait pas mieux de trier par nombre de PF plutôt qui contient ces valeurs et d'indiquer ce nombre dans le label du selecteur.
Cela permettrait aux utilisateurs d'anticiper le nombre de PF que leur sélection va retourner.

Qu'en pensez vous ?

**Comment by SophieForcadell** [comment]
Tu veux dire que cela permettrait aux utilisateurs qui voient qu'un tout petit nombre de PF qui correspondent à leur sélection d'anticiper qu'il doivent compléter avec une autre orthographe ? (suis pas sûre de bien comprendre...)

**Comment by paulgirard** [comment]
oui c'est ça.
Par exemple pour le champs liste le sélecteur proposerait: 
Liste: droite 
- Union de la Droite 87
- Ni vieille droite ni fausse gauche 1

Pour résumer ça classerait les valeurs proposées par fréquence.

**Comment by SophieForcadell** [comment]
Ca me semble bien tenir la route.

**Comment by paulgirard** [comment]
Est ce que tu veux en parler au groupe avant de confirmer ? 
Ça va nous demander un peu de temps d'adaptation, il ne faudrait pas qu'on nous demande de revenir en arrière sur ce point.

**Comment by SophieForcadell** [comment]
oui, je viens de faire un mail dans ce sens.
