### ISSUE TITLE
Ordre des valeurs du champ numéro (de circonscription)

### ISSUE THREAD

**Issue by SophieForcadell** [SciencesPoDRIS/archelec4#24]
Les numéros ne sont pas dans le bon ordre (comme si c'était des chaines de caractères au lieu de valeurs numériques)

**Comment by paulgirard** [comment]
Je ne comprends pas ce qui ne marche pas voir copie d'écran:
![image](https://user-images.githubusercontent.com/193478/123931447-cba46a00-d990-11eb-8c51-deb93a179520.png)

**Comment by SophieForcadell** [comment]
Il s'agit des numéros de circonscription et non de département

**Comment by paulgirard** [comment]
au temps pour moi...
On pensait avoir préfixé les numéros des circonscription < 10 par un 0 ce qui supprimerait ce problème mais je constate que ça ne fonctionne pas. A regarder
