### ISSUE TITLE
Données Décoration erronées

### ISSUE THREAD

**Issue by SophieForcadell** [SciencesPoDRIS/archelec4#3]
**Quel est le problème ?**
Les items du menu "Décorations" sont erronés

**Quel est le comportement attendu ?**
Lister oui ou non comme items du menu Décorations

**Comment reproduire le problème ?**

1. aller à cette URL: https://archelec.sciencespo.fr/explorer
2. cliquer sur le terme "sélectionner" en dessous de l'intitulé de menu "Décoration"
3. constater l'erreur

**Copie d'écran**
![Capture d’écran 2021-06-07 à 10 02 39](https://user-images.githubusercontent.com/85479317/120981288-d3009b00-c777-11eb-9c4e-eb7fe31b51b3.png)

**Comment by paulgirard** [comment]
Les champs sont rempi automatiquement à partir de ce que contient Internet Archive.
Le problème "Marié: père de famille" est constaté dans cette PF : https://archelec.sciencespo.fr/profession/EL198_L_1993_03_092_01_1_PF_020
A corriger côté Internet Archive à priori.

**Comment by SophieForcadell** [comment]
Oui, je m'en suis rendue compte après... Désolée !

**Comment by paulgirard** [comment]
Problème du champs Décorations à corriger dans Internet Archive : https://archelec.sciencespo.fr/explorer?candidats.decorations=d%C3%A9corations%7CMari%C3%A9+%3B+p%C3%A8re+de+famille%7CD%C3%A9coration%7CPF%7Cnon+renseign%C3%A9

**Comment by PaulineBougon** [comment]
données corrigées !
