### ISSUE TITLE
Champs de recherche Tour multiselect

### ISSUE THREAD

**Issue by diegantobass** [SciencesPoDRIS/archelec4#6]
**Quel est le problème ?**
Si je sélectionne tour 1 ou 2, je ne peux plus annuler mon choix, choisir les deux, ou n'en choisir aucun (ça revient au même : si j'en choisis un, je peux plus avoir les deux)

**Quel est le comportement attendu ?**
Je devrais pouvoir sélectionner les deux après avoir malencontreusement choisi l'un des deux

**Comment reproduire le problème ?**

1. aller à cette URL: https://archelec.sciencespo.fr/
2. cliquer sur le menu déroulant du champ Tour
3. choisir tour 1
4. constater l'impossibilité de désélectionner 1 ou de sélectionner 2 en plus

**Copie d'écran**
![headshot_20210608_102402](https://user-images.githubusercontent.com/9825192/121150724-0e689b80-c844-11eb-9c85-013cd5dee0f0.jpeg)

**Contexte**
 
 - Appareil utilisé : ordinateur
 - OS: Kubuntu 2à
 - Browser : Firefox 89

**Comment by paulgirard** [comment]
Je confirme.
solution rapide: on permet la multisélection ce qui permettra de supprimer un choix.

**Comment by diegantobass** [comment]
Ça me va
